# Application Name
spring.application.name=Kartland

# MySQL Database (Hostinger)
spring.datasource.url=jdbc:mysql://localhost:3306/u404053949_kartland_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=u404053949_kartland_pune
spring.datasource.password=Kartland@16
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
Database Host: 	62.72.28.204

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Spring Security
spring.security.user.name=user
spring.security.user.password=admin_password
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=s3458540@gmail.com
spring.mail.password=yghclcuvrjktinfo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
