spring.application.name=Kartland
spring.datasource.url=jdbc:mysql://localhost:3306/kartland
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql:true

spring.security.user.name=user
spring.security.user.password=admin_password
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=s3458540@gmail.com
spring.mail.password=yghclcuvrjktinfo  
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true